"use client";

import { useEffect, useRef, useState } from "react";
import { actorLabel, formatAdminDate, operationPresentation, operationSummary } from "@/components/admin/presentation";
import { Button } from "@/components/ui/button";
import { MaterialIcon } from "@/components/ui/icon";

export type OperationLogRecord = { id: string; createdAt: string; actorType: string; action: string; entityType: string | null; entityId: string | null; metadata: unknown };

export function OperationLogsTable({ logs }: { logs: OperationLogRecord[] }) {
  const [selected, setSelected] = useState<OperationLogRecord | null>(null);
  return <><div className="overflow-x-auto rounded-xl border border-[var(--border)] bg-white shadow-[var(--shadow-card)]"><table className="w-full min-w-[920px] text-left text-sm"><thead className="border-b border-[var(--border-subtle)] bg-[var(--surface-subtle)] text-xs text-[var(--text-muted)]"><tr><th className="px-5 py-3.5 font-semibold sm:px-6">时间</th><th className="px-5 py-3.5 font-semibold">执行者</th><th className="px-5 py-3.5 font-semibold">操作</th><th className="px-5 py-3.5 font-semibold">对象</th><th className="px-5 py-3.5 font-semibold">摘要</th><th className="px-5 py-3.5 text-right font-semibold sm:px-6">详情</th></tr></thead><tbody>{logs.map((entry) => { const presentation = operationPresentation(entry.action); return <tr key={entry.id} className="border-b border-[var(--border-subtle)] last:border-b-0"><td className="px-5 py-4 whitespace-nowrap text-xs text-[var(--text-muted)] sm:px-6">{formatAdminDate(entry.createdAt, true)}</td><td className="px-5 py-4 text-[var(--text-secondary)]">{actorLabel(entry.actorType)}</td><td className="px-5 py-4"><span className="flex items-center gap-2 font-semibold text-[var(--text-primary)]"><MaterialIcon name={presentation.icon} size={19} className="text-[var(--text-secondary)]" />{presentation.title}</span></td><td className="px-5 py-4 text-xs text-[var(--text-secondary)]">{resourceLabel(entry.entityType)}{entry.entityId ? <span className="ml-1 text-[var(--text-muted)]">· {entry.entityId.slice(0, 8)}</span> : null}</td><td className="max-w-[320px] px-5 py-4 text-xs leading-5 text-[var(--text-secondary)]">{operationSummary(entry.metadata)}</td><td className="px-5 py-4 text-right sm:px-6"><Button type="button" variant="ghost" size="sm" onClick={() => setSelected(entry)}>查看</Button></td></tr>; })}</tbody></table></div><LogDetailDialog log={selected} onClose={() => setSelected(null)} /></>;
}

function LogDetailDialog({ log, onClose }: { log: OperationLogRecord | null; onClose: () => void }) {
  const closeButton = useRef<HTMLButtonElement>(null);
  useEffect(() => { if (!log) return; const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; document.addEventListener("keydown", onKeyDown); window.setTimeout(() => closeButton.current?.focus(), 0); return () => document.removeEventListener("keydown", onKeyDown); }, [log, onClose]);
  if (!log) return null;
  const presentation = operationPresentation(log.action);
  const metadata = stringifyMetadata(log.metadata);
  return <div className="fixed inset-0 z-[70] flex justify-end bg-[#17242d]/35" role="presentation"><button type="button" className="absolute inset-0 cursor-default" aria-label="关闭运维记录详情" onClick={onClose} /><aside role="dialog" aria-modal="true" aria-labelledby="operation-log-detail-title" className="relative flex h-full w-full max-w-[500px] flex-col bg-white shadow-[-18px_0_48px_rgba(23,36,45,0.20)]"><div className="flex items-start justify-between gap-4 border-b border-[var(--border-subtle)] p-5"><div><p className="text-xs font-semibold tracking-[0.08em] text-[var(--brand)]">运维记录详情</p><h2 id="operation-log-detail-title" className="mt-2 text-xl font-semibold text-[var(--text-primary)]">{presentation.title}</h2></div><button ref={closeButton} type="button" aria-label="关闭运维记录详情" className="grid size-10 place-items-center rounded-lg text-[var(--text-secondary)] hover:bg-[var(--surface-muted)]" onClick={onClose}><MaterialIcon name="close" size={21} /></button></div><div className="flex-1 overflow-y-auto p-5"><dl className="space-y-4"><Detail label="时间" value={formatAdminDate(log.createdAt, true)} /><Detail label="执行者" value={actorLabel(log.actorType)} /><Detail label="对象" value={resourceLabel(log.entityType)} /><Detail label="安全摘要" value={operationSummary(log.metadata)} /><Detail label="内部事件代码" value={log.action} /></dl><details className="mt-7 rounded-xl border border-[var(--border)] bg-[var(--surface-subtle)]"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 px-4 py-3 text-sm font-semibold text-[var(--text-primary)]"><span className="flex items-center gap-2"><MaterialIcon name="data_object" size={19} />查看原始安全元数据</span><MaterialIcon name="expand_more" size={19} /></summary><pre className="max-h-64 overflow-auto border-t border-[var(--border-subtle)] bg-white p-4 font-mono text-xs leading-6 text-[var(--text-primary)]">{metadata}</pre></details></div><div className="border-t border-[var(--border-subtle)] p-5"><Button type="button" variant="secondary" className="w-full" onClick={onClose}>关闭</Button></div></aside></div>;
}

function Detail({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-medium text-[var(--text-muted)]">{label}</dt><dd className="mt-1.5 text-sm font-semibold leading-6 text-[var(--text-primary)]">{value}</dd></div>; }
function resourceLabel(type: string | null) { return ({ campaign: "抽奖活动", email_domain_rule: "邮箱规则", smtp_config: "SMTP 配置", email_template: "邮件模板", email_job: "邮件任务", settings: "系统设置" } as Record<string, string>)[type ?? ""] ?? (type ? "系统对象" : "-"); }
function stringifyMetadata(value: unknown) { try { return value ? JSON.stringify(value, null, 2) : "{}"; } catch { return "{}"; } }
